// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pokerdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompleteHand(ctx context.Context, arg CompleteHandParams) (Hand, error)
	CountHandsBetween(ctx context.Context, arg CountHandsBetweenParams) (int64, error)
	GetHandByID(ctx context.Context, id uuid.UUID) (Hand, error)
	InsertHand(ctx context.Context, arg InsertHandParams) (Hand, error)
	InsertHandAction(ctx context.Context, arg InsertHandActionParams) (HandAction, error)
	ListHandActionsByHand(ctx context.Context, handID uuid.UUID) ([]HandAction, error)
	ListHandsForAdmin(ctx context.Context, arg ListHandsForAdminParams) ([]Hand, error)
}

var _ Querier = (*Queries)(nil)
