// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pokerdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeHand = `-- name: CompleteHand :one
UPDATE hands
SET
  status         = 'complete',
  pot_total      = $2,
  completed_at   = now()
WHERE id = $1
  AND status = 'in_progress'
RETURNING
  id, room_id, hand_number, dealer_seat, small_blind, big_blind, status, pot_total, created_at, completed_at
`

type CompleteHandParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	PotTotal *int64    `db:"pot_total" json:"pot_total"`
}

func (q *Queries) CompleteHand(ctx context.Context, arg CompleteHandParams) (Hand, error) {
	row := q.db.QueryRow(ctx, completeHand, arg.ID, arg.PotTotal)
	var i Hand
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.HandNumber,
		&i.DealerSeat,
		&i.SmallBlind,
		&i.BigBlind,
		&i.Status,
		&i.PotTotal,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countHandsBetween = `-- name: CountHandsBetween :one
SELECT count(*)::bigint AS cnt
FROM hands
WHERE created_at >= $1 AND created_at < $2
`

type CountHandsBetweenParams struct {
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `db:"created_at_2" json:"created_at_2"`
}

func (q *Queries) CountHandsBetween(ctx context.Context, arg CountHandsBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHandsBetween, arg.CreatedAt, arg.CreatedAt_2)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getHandByID = `-- name: GetHandByID :one
SELECT
  id, room_id, hand_number, dealer_seat, small_blind, big_blind, status, pot_total, created_at, completed_at
FROM hands
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetHandByID(ctx context.Context, id uuid.UUID) (Hand, error) {
	row := q.db.QueryRow(ctx, getHandByID, id)
	var i Hand
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.HandNumber,
		&i.DealerSeat,
		&i.SmallBlind,
		&i.BigBlind,
		&i.Status,
		&i.PotTotal,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertHand = `-- name: InsertHand :one
INSERT INTO hands (id, room_id, hand_number, dealer_seat, small_blind, big_blind, status, pot_total)
VALUES ($1, $2, $3, $4, $5, $6, 'in_progress', $7)
RETURNING
  id, room_id, hand_number, dealer_seat, small_blind, big_blind, status, pot_total, created_at, completed_at
`

type InsertHandParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	RoomID     string    `db:"room_id" json:"room_id"`
	HandNumber int32     `db:"hand_number" json:"hand_number"`
	DealerSeat int32     `db:"dealer_seat" json:"dealer_seat"`
	SmallBlind int64     `db:"small_blind" json:"small_blind"`
	BigBlind   int64     `db:"big_blind" json:"big_blind"`
	PotTotal   *int64    `db:"pot_total" json:"pot_total"`
}

func (q *Queries) InsertHand(ctx context.Context, arg InsertHandParams) (Hand, error) {
	row := q.db.QueryRow(ctx, insertHand,
		arg.ID,
		arg.RoomID,
		arg.HandNumber,
		arg.DealerSeat,
		arg.SmallBlind,
		arg.BigBlind,
		arg.PotTotal,
	)
	var i Hand
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.HandNumber,
		&i.DealerSeat,
		&i.SmallBlind,
		&i.BigBlind,
		&i.Status,
		&i.PotTotal,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertHandAction = `-- name: InsertHandAction :one
INSERT INTO hand_actions (hand_id, action_seq, table_seat, hand_player_index, user_id, action_type, amount, street, is_timeout, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
  id, hand_id, action_seq, table_seat, hand_player_index, user_id, action_type, amount, street, is_timeout, metadata, created_at
`

type InsertHandActionParams struct {
	HandID          uuid.UUID   `db:"hand_id" json:"hand_id"`
	ActionSeq       int32       `db:"action_seq" json:"action_seq"`
	TableSeat       *int32      `db:"table_seat" json:"table_seat"`
	HandPlayerIndex *int32      `db:"hand_player_index" json:"hand_player_index"`
	UserID          pgtype.UUID `db:"user_id" json:"user_id"`
	ActionType      string      `db:"action_type" json:"action_type"`
	Amount          *int64      `db:"amount" json:"amount"`
	Street          string      `db:"street" json:"street"`
	IsTimeout       bool        `db:"is_timeout" json:"is_timeout"`
	Metadata        []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) InsertHandAction(ctx context.Context, arg InsertHandActionParams) (HandAction, error) {
	row := q.db.QueryRow(ctx, insertHandAction,
		arg.HandID,
		arg.ActionSeq,
		arg.TableSeat,
		arg.HandPlayerIndex,
		arg.UserID,
		arg.ActionType,
		arg.Amount,
		arg.Street,
		arg.IsTimeout,
		arg.Metadata,
	)
	var i HandAction
	err := row.Scan(
		&i.ID,
		&i.HandID,
		&i.ActionSeq,
		&i.TableSeat,
		&i.HandPlayerIndex,
		&i.UserID,
		&i.ActionType,
		&i.Amount,
		&i.Street,
		&i.IsTimeout,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listHandActionsByHand = `-- name: ListHandActionsByHand :many
SELECT
  id, hand_id, action_seq, table_seat, hand_player_index, user_id, action_type, amount, street, is_timeout, metadata, created_at
FROM hand_actions
WHERE hand_id = $1
ORDER BY action_seq ASC
`

func (q *Queries) ListHandActionsByHand(ctx context.Context, handID uuid.UUID) ([]HandAction, error) {
	rows, err := q.db.Query(ctx, listHandActionsByHand, handID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HandAction
	for rows.Next() {
		var i HandAction
		if err := rows.Scan(
			&i.ID,
			&i.HandID,
			&i.ActionSeq,
			&i.TableSeat,
			&i.HandPlayerIndex,
			&i.UserID,
			&i.ActionType,
			&i.Amount,
			&i.Street,
			&i.IsTimeout,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandsForAdmin = `-- name: ListHandsForAdmin :many
SELECT
  id, room_id, hand_number, dealer_seat, small_blind, big_blind, status, pot_total, created_at, completed_at
FROM hands
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListHandsForAdminParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListHandsForAdmin(ctx context.Context, arg ListHandsForAdminParams) ([]Hand, error) {
	rows, err := q.db.Query(ctx, listHandsForAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hand
	for rows.Next() {
		var i Hand
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.HandNumber,
			&i.DealerSeat,
			&i.SmallBlind,
			&i.BigBlind,
			&i.Status,
			&i.PotTotal,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
