// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auditlog

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           int64              `db:"id" json:"id"`
	ActorUserID  uuid.UUID          `db:"actor_user_id" json:"actor_user_id"`
	Action       string             `db:"action" json:"action"`
	ResourceType *string            `db:"resource_type" json:"resource_type"`
	ResourceID   *string            `db:"resource_id" json:"resource_id"`
	Payload      []byte             `db:"payload" json:"payload"`
	IpAddress    *string            `db:"ip_address" json:"ip_address"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Hand struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	RoomID      string             `db:"room_id" json:"room_id"`
	HandNumber  int32              `db:"hand_number" json:"hand_number"`
	DealerSeat  int32              `db:"dealer_seat" json:"dealer_seat"`
	SmallBlind  int64              `db:"small_blind" json:"small_blind"`
	BigBlind    int64              `db:"big_blind" json:"big_blind"`
	Status      string             `db:"status" json:"status"`
	PotTotal    *int64             `db:"pot_total" json:"pot_total"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type HandAction struct {
	ID              int64              `db:"id" json:"id"`
	HandID          uuid.UUID          `db:"hand_id" json:"hand_id"`
	ActionSeq       int32              `db:"action_seq" json:"action_seq"`
	TableSeat       *int32             `db:"table_seat" json:"table_seat"`
	HandPlayerIndex *int32             `db:"hand_player_index" json:"hand_player_index"`
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	ActionType      string             `db:"action_type" json:"action_type"`
	Amount          *int64             `db:"amount" json:"amount"`
	Street          string             `db:"street" json:"street"`
	IsTimeout       bool               `db:"is_timeout" json:"is_timeout"`
	Metadata        []byte             `db:"metadata" json:"metadata"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Transaction struct {
	ID           int64              `db:"id" json:"id"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	Amount       int64              `db:"amount" json:"amount"`
	BalanceAfter int64              `db:"balance_after" json:"balance_after"`
	Type         string             `db:"type" json:"type"`
	HandID       pgtype.UUID        `db:"hand_id" json:"hand_id"`
	Metadata     []byte             `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Role         string             `db:"role" json:"role"`
	ChipsBalance int64              `db:"chips_balance" json:"chips_balance"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
