// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package auditlog

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (actor_user_id, action, resource_type, resource_id, payload, ip_address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
  id, actor_user_id, action, resource_type, resource_id, payload, ip_address, created_at
`

type InsertAuditLogParams struct {
	ActorUserID  uuid.UUID `db:"actor_user_id" json:"actor_user_id"`
	Action       string    `db:"action" json:"action"`
	ResourceType *string   `db:"resource_type" json:"resource_type"`
	ResourceID   *string   `db:"resource_id" json:"resource_id"`
	Payload      []byte    `db:"payload" json:"payload"`
	IpAddress    *string   `db:"ip_address" json:"ip_address"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Payload,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Payload,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}
