// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auditlog

import (
	"context"
)

type Querier interface {
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
}

var _ Querier = (*Queries)(nil)
