// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Sempre: uma linha em transactions + o novo chips_balance, na mesma transação
	// (delta negativo = saída de saldo, positivo = entrada)
	ApplyChipsDelta(ctx context.Context, arg ApplyChipsDeltaParams) (User, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListUsersForAdmin(ctx context.Context, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error)
	SearchUsersForAdmin(ctx context.Context, arg SearchUsersForAdminParams) ([]SearchUsersForAdminRow, error)
}

var _ Querier = (*Queries)(nil)
