// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package user

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyChipsDelta = `-- name: ApplyChipsDelta :one
WITH u AS (
  SELECT users.id, users.chips_balance
  FROM users
  WHERE users.id = $1
  FOR UPDATE
),
t AS (
  INSERT INTO transactions (user_id, amount, balance_after, type, hand_id, metadata, created_at)
  SELECT
    u.id,
    $2,
    u.chips_balance + $2,
    $3,
    $4::uuid,
    COALESCE($5::jsonb, '{}'::jsonb),
    now()
  FROM u
  WHERE u.chips_balance + $2 >= 0
  RETURNING transactions.id, transactions.balance_after
)
UPDATE users
SET
  chips_balance = t.balance_after,
  updated_at    = now()
FROM t
WHERE users.id = (SELECT u.id FROM u)
RETURNING
  users.id,
  users.email,
  users.password_hash,
  users.role,
  users.chips_balance,
  users.created_at,
  users.updated_at
`

type ApplyChipsDeltaParams struct {
	ID       uuid.UUID   `db:"id" json:"id"`
	Amount   int64       `db:"amount" json:"amount"`
	Type     string      `db:"type" json:"type"`
	HandID   pgtype.UUID `db:"hand_id" json:"hand_id"`
	Metadata []byte      `db:"metadata" json:"metadata"`
}

// Sempre: uma linha em transactions + o novo chips_balance, na mesma transação
// (delta negativo = saída de saldo, positivo = entrada)
func (q *Queries) ApplyChipsDelta(ctx context.Context, arg ApplyChipsDeltaParams) (User, error) {
	row := q.db.QueryRow(ctx, applyChipsDelta,
		arg.ID,
		arg.Amount,
		arg.Type,
		arg.HandID,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ChipsBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, role, chips_balance, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	Role         string `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ChipsBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, chips_balance, created_at, updated_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ChipsBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, chips_balance, created_at, updated_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ChipsBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersForAdmin = `-- name: ListUsersForAdmin :many
SELECT id, email, role, chips_balance, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersForAdminParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListUsersForAdminRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	Role         string             `db:"role" json:"role"`
	ChipsBalance int64              `db:"chips_balance" json:"chips_balance"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListUsersForAdmin(ctx context.Context, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersForAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersForAdminRow
	for rows.Next() {
		var i ListUsersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.ChipsBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersForAdmin = `-- name: SearchUsersForAdmin :many
SELECT id, email, role, chips_balance, created_at, updated_at
FROM users
WHERE email ILIKE $1
ORDER BY email ASC
LIMIT $2 OFFSET $3
`

type SearchUsersForAdminParams struct {
	Email  string `db:"email" json:"email"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

type SearchUsersForAdminRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	Role         string             `db:"role" json:"role"`
	ChipsBalance int64              `db:"chips_balance" json:"chips_balance"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SearchUsersForAdmin(ctx context.Context, arg SearchUsersForAdminParams) ([]SearchUsersForAdminRow, error) {
	rows, err := q.db.Query(ctx, searchUsersForAdmin, arg.Email, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersForAdminRow
	for rows.Next() {
		var i SearchUsersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.ChipsBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
